### ISSUE TITLE
(RuntimeError)

### ISSUE THREAD

**Issue by juragandotid** [timrogers/amex#4]
There is i'm use my amex account but have disabled account, i'm used for test and igot error : 

client.rb:37:in `accounts': There was a problem logging in to American Express. (RuntimeError)
 from validate.rb:13:in `<main>'

source from client.rb line 35 to 38 :
if xml.css('ServiceResponse Status').text != "success"
        raise "There was a problem logging in to American Express."
      else

Help me pleasee, Thank you.

**Comment by timrogers** [comment]
This gem is very old and most likely won't work with banks' modern systems. Sorry 🙈  I'll add a notice to that effect to the readme when I get a chance.
